//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.StudentBasicInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtID;
		protected global::System.Web.UI.WebControls.TextBox txtXingMing;
		protected global::System.Web.UI.WebControls.TextBox txtJiGuan;
		protected global::System.Web.UI.WebControls.TextBox txtMinZu;
		protected global::System.Web.UI.WebControls.TextBox txtShengYuanDi;
		protected global::System.Web.UI.WebControls.TextBox txtShengRi;
		protected global::System.Web.UI.WebControls.TextBox txtXingBie;
		protected global::System.Web.UI.WebControls.TextBox txtTag;
		protected global::System.Web.UI.WebControls.TextBox txtTouXiang;
		protected global::System.Web.UI.WebControls.TextBox txtMiMa;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
