//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.StudentGraduateInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtXingMing;
		protected global::System.Web.UI.WebControls.TextBox txtXueLi;
		protected global::System.Web.UI.WebControls.TextBox txtRuXueShiJian;
		protected global::System.Web.UI.WebControls.TextBox txtBiYeShiJian;
		protected global::System.Web.UI.WebControls.TextBox txtBiJiZhengShuHao;
		protected global::System.Web.UI.WebControls.TextBox txtXueWeiZhengHao;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
